apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: f5xl0cppx-dotnet-basic
  janus-idp.io/tekton: f5xl0cppx-dotnet-basic
  backstage.io/kubernetes-id: f5xl0cppx-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: f5xl0cppx-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
